scripts = {
    cyrillic: {
        bicameral: true,
        users: 300000000,
        comingSoon: false,
        location: ["Eastern Europe", "Central Asia"],
        languages: ["Russian", "Ukrainian", "Bulgarian", "Uzbek", "others"],
        difficulty: 1,
        info: "The Cyrillic alphabet was created by brothers Cyril and Methodius in the 9th century in order to spread Christianity to the Slavs. Many Slavic languages use Cyrillic, as well as other languages like Mongolian and Kazakh.",
        langs: {
            russian: {
                info: "The Russian language is one of the most spoken in the world, and is one of six official United Nations languages. Despite the collapse of the Soviet Union, the Russian language remains popular in Eastern Europe and parts of Central Asia, and is spoken by significant minorities in the Baltic states.",
                users: 250000000,
                location: ["Russia", "Belarus", "Kazakhstan", "others"],
                specialLetters: [],
                transliteration_explanations: {
                    "я": "'a' after consonants, otherwise 'ia'",
                    "ю": "'u' after consonants, otherwise 'iu'",
                    "е": "'e' after consonants, otherwise 'ie'",
                    "ё": "'o' after consonants, otherwise 'io'",
                    "ь": "The preceding consonant is made 'soft' and palatized - indicated with a ', while the following vowel is fully pronounced (i.e. ё is 'io' not 'o')",
                    "ъ": `The preceding consonant is made 'hard' and not palatized - indicated with a ", while the vowel afterwards is fully pronounced (i.e. я is 'ia' not 'a')`,
                },
                alphabet: { 
                    "а": "a", 
                    "б": "b", 
                    "в": "v", 
                    "г": "g", 
                    "д": "d", 
                    "е": "ie,e", 
                    "ё": "io,o", 
                    "ж": "zh", 
                    "з": "z", 
                    "и": "i", 
                    "й": "i", 
                    "к": "k", 
                    "л": "l", 
                    "м": "m", 
                    "н": "n", 
                    "о": "o", 
                    "п": "p", 
                    "р": "r",
                    "с": "s", 
                    "т": "t", 
                    "у": "u", 
                    "ф": "f", 
                    "х": "kh",
                    "ц": "ts",
                    "ч": "ch", 
                    "ш": "sh", 
                    "щ": "shch", 
                    "ъ": `"`, 
                    "ы": "y", 
                    "ь": "'", 
                    "э": "e", 
                    "ю": "iu,u", 
                    "я": "ia,a",
                }, 
                toIPA: {
                    "y": "ɨ",
                    "'": "",
                    "\"": "",
                    "zh": "ʒ",
                    "sh": "ʂ",
                    "shch": "ɕ",
                    "ch": "tʃ",
                    "kh": "χ",
                    "a": "ɑ",
                    "e": "ɛ",
                    "iu": "ju",
                    "ia": "ja",
                    "io": "jo",
                    "ie": "je",
                },
                levelList: [ 
                    { 
                        letters: ["а", "к", "м", "о", "с", "т"], 
                        words: {"кокос": "coconut", "там": "there", "моток": "coiled yarn"}, 
                    },
                    { 
                        letters: ["в", "е", "н", "р", "х", "б"], 
                        words: {"нет": "no", "место": "a place", "работа": "work", "москва": "moscow", "страх": "fear"}, 
                    }, 
                    { 
                        letters: ["и", "г", "д", "л", "п", "у"], 
                        words: {"рука": "arm", "где": "where?", "подумала": "thought", "минута": "minute"}, 
                    }, 
                    { 
                        letters: ["й", "з", "ж", "ч", "ц", "э"], 
                        words: {"другой": "other", "сразу": "at once", "мужчина": "the man", "конец": "end", "экономический": "economic"}, 
                    }, 
                    { 
                        letters: ["ё", "я", "ю", "ш", "щ", "ы"], 
                        words: {"чёрный": "black", "хозяин": "proprietor", "следующий": "next", "пришлый": "foreign"}, 
                    }, 
                    { 
                        letters: ["ф", "ь", "ъ"], 
                        words: {"объяснить": "explain", "вздохнуть": "sigh", "информация": "information"}, 
                    }, 
                ],
            },
            bulgarian: {
                info: "Bulgarian is a South Slavic language spoken principally in the Republic of Bulgaria. Bulgarian is most similar to Macedonian, and these two languages lack grammatical case (unlike all other Slavic languages). In the Republic of Moldova, there is a majority Bulgarian-speaking municipality called Taraclia, and Bulgarians are a sizeable minority in the southern Ukrainian region of Budjak.",
                users: 9000000,
                location: ["Bulgaria"],
                specialLetters: ["ŭ"],
                transliteration_explanations: {},
                alphabet: { 
                    "а": "a", 
                    "б": "b", 
                    "в": "v", 
                    "г": "g", 
                    "д": "d", 
                    "е": "e", 
                    "ж": "zh", 
                    "з": "z", 
                    "и": "i", 
                    "й": "y", 
                    "к": "k", 
                    "л": "l", 
                    "м": "m", 
                    "н": "n", 
                    "о": "o", 
                    "п": "p", 
                    "р": "r",
                    "с": "s", 
                    "т": "t", 
                    "у": "u", 
                    "ф": "f", 
                    "х": "kh",
                    "ц": "ts", 
                    "ч": "ch", 
                    "ш": "sh", 
                    "щ": "sht", 
                    "ъ": "ŭ", 
                    "ы": "y", 
                    "ь": "'", 
                    "э": "e", 
                    "ю": "yu", 
                    "я": "ya",
                }, 
                toIPA: {
                    "y": "j",
                    "'": "",
                    "ŭ": "ɤ",
                    "zh": "ʒ",
                    "sh": "ʃ",
                    "sht": "ʃt",
                    "ch": "tʃ",
                    "kh": "χ",
                    "a": "ɑ",
                    "e": "ɛ",
                    "yu": "ju",
                    "ya": "ja",
                },
                levelList: [ 
                    { 
                        letters: ["а", "к", "м", "о", "р", "т"], 
                        words: {"какао": "cacao", "там": "there", "мотор": "motor"}, 
                    },
                    { 
                        letters: ["в", "е", "н", "х", "б", "с"], 
                        words: {"не": "no", "работа": "work", "москва": "moscow", "страх": "fear"}, 
                    }, 
                    { 
                        letters: ["и", "г", "д", "л", "п", "у", "ъ"], 
                        words: {"ръка": "arm", "където?": "where?", "мисъл": "thought", "минута": "minute"}, 
                    }, 
                    {
                        letters: ["й", "з", "ж", "ч", "ц"], 
                        words: {"незабавно": "immediately", "мъжът": "the man", "икономически": "economic"}, 
                    }, 
                    { 
                        letters: ["я", "ю", "ш", "щ", "ф", "ь"], 
                        words: {"юли": "july", "обясни": "explain", "въздишка": "sigh", "инфраструктура": "infrastructure"}, 
                    }, 
                ],
            },
            macedonian: {
                info: "Macedonian is a South Slavic language related to Bulgarian and Serbian. While this language comes from the Balkans, there is actually a large Macedonian-speaking diaspora in Australia. There are six original letters in the Macedonian alphabet that don't appear in other varities of Cyrillic.",
                users: 3000000,
                location: ["Macedonia"],
                specialLetters: [],
                transliteration_explanations: {},
                alphabet: { 
                    "а": "a", 
                    "б": "b", 
                    "в": "v", 
                    "г": "g", 
                    "д": "d",
                    "ѓ": "gj",
                    "е": "e", 
                    "ж": "zh", 
                    "з": "z",
                    "ѕ": "dz",
                    "и": "i", 
                    "ј": "j", 
                    "к": "k", 
                    "л": "l", 
                    "љ": "lj",
                    "м": "m", 
                    "н": "n", 
                    "њ": "nj",
                    "о": "o", 
                    "п": "p", 
                    "р": "r",
                    "с": "s", 
                    "т": "t", 
                    "ќ": "kj",
                    "у": "u", 
                    "ф": "f", 
                    "х": "kh",
                    "ц": "ts",
                    "ч": "ch",
                    "џ": "dzh",
                    "ш": "sh",
                    " ": " ",
                }, 
                toIPA: {
                    "nj": "ɲ",
                    "lj": "ʎ",
                    "kj": "c",
                    "gj": "ɟ",
                    "dzh": "dʒ",
                    "zh": "ʒ",
                    "sh": "ʃ",
                    "ch": "tʃ",
                    "kh": "χ",
                    "a": "ɑ",
                    "e": "ɛ",
                },
                levelList: [
                    { 
                        letters: ["а", "к", "м", "о", "р", "т"], 
                        words: {"какао": "cacao", "тоа": "that", "мотор": "motor"}, 
                    },
                    { 
                        letters: ["в", "е", "н", "х", "б", "с"], 
                        words: {"не": "no", "работа": "work", "москва": "moscow", "страх": "fear"}, 
                    }, 
                    { 
                        letters: ["и", "г", "д", "л", "п", "у", "ј"], 
                        words: {"утро": "day", "каде?": "where?", "мисла": "thought", "минута": "minute"}, 
                    }, 
                    {
                        letters: ["з", "ж", "ч", "ц", "џ", "ѕ"], 
                        words: {"џенова": "genova (italian city)", "мажот": "the man", "ѕидот": "the wall", "четири": "four", "македонски": "macedonian"}, 
                    }, 
                    { 
                        letters: ["ш", "ф", "ќ", "ѓ", "њ", "љ"], 
                        words: {"формирањето": "formation", "комунистичка партија": "communist party", "виљушка": "fork", "меѓународната": "international"}, 
                    }, 
                ],
            },
            serbian: {
                info: "Serbian is a South Slavic language related to Bulgarian and Serbian. While this language comes from the Balkans, there is actually a large Macedonian-speaking diaspora in Australia. There are six original letters in the Macedonian alphabet that don't appear in other varities of Cyrillic.",
                users: 9500000,
                specialLetters: ["đ", "ž", "ć", "č", "š"],
                location: ["Serbia", "Bosnia", "Montenegro"],
                transliteration_explanations: {},
                alphabet: { 
                    "а": "a", 
                    "б": "b", 
                    "в": "v", 
                    "г": "g",
                    "д": "d",
                    "ђ": "đ",
                    "е": "e", 
                    "ж": "zh", 
                    "з": "z",
                    "и": "i", 
                    "ј": "j", 
                    "к": "k", 
                    "л": "l", 
                    "љ": "lj",
                    "м": "m", 
                    "н": "n", 
                    "њ": "nj",
                    "о": "o", 
                    "п": "p", 
                    "р": "r",
                    "с": "s", 
                    "т": "t",
                    "ћ": "ć",
                    "у": "u", 
                    "ф": "f", 
                    "х": "kh",
                    "ц": "ts", 
                    "ч": "č", 
                    "џ": "dž",
                    "ш": "š",
                }, 
                toIPA: {
                    "c": "ts",
                    "nj": "ɲ",
                    "lj": "ʎ",
                    "dž": "ɖʐ",
                    "ž": "ʐ",
                    "š": "ʂ",
                    "ć": "tɕ",
                    "č": "tʂ",
                    "a": "ɑ",
                    "e": "ɛ",
                },
                levelList: [
                    { 
                        letters: ["а", "к", "м", "о", "р", "т"], 
                        words: {"какао": "cacao", "мотор": "motor"}, 
                    },
                    { 
                        letters: ["в", "е", "н", "х", "б", "с"], 
                        words: {"не": "no", "работа": "work", "страх": "fear"}, 
                    }, 
                    { 
                        letters: ["и", "г", "д", "л", "п", "у"], 
                        words: {"дан": "day", "где?": "where?", "мислио": "thought", "радити": "work"}, 
                    }, 
                    {
                        letters: ["з", "ж", "ч", "ц", "џ", "ј"], 
                        words: {"санџак": "sanjak (geographic region)", "народноослободилачки": "national liberation", "југославија": "yugoslavia"}, 
                    }, 
                    { 
                        letters: ["ш", "ф", "ћ", "ђ", "њ", "љ"],
                        words: {"ђенова": "genova (italian city)", "оснивање": "foundation", "федерација": "federation", "најзаступљеније": "the most represented"}, 
                    }, 
                ],
            },
        },
    },
    greek: {
        bicameral: true,
        comingSoon: false,
        users:  13400000,
        location: ["Greece", "Cyprus"],
        languages: ["Greek"],
        difficulty: 1,
        case: true,
        info: "Since antiquity, the Greek language has been written in its own alphabet. Latin, Cyrillic, Georgian, and Armenian all originally come from this source alphabet. Although the Greek language has changed a lot in the past 3,000 years, it still uses its original alphabet. Many Greek letters are used in science, mathematics, and other fields.",
        langs: {
            greek: {
                alphabet: {
                    "α": "a",
                    "β": "v",
                    "γ": "g,y",
                    "δ": "dh",
                    "ε": "e",
                    "ζ": "z",
                    "η": "i",
                    "θ": "th",
                    "ι": "i",
                    "κ": "k",
                    "λ": "l",
                    "μ": "m",
                    "ν": "n",
                    "ξ": "ks",
                    "ο": "o",
                    "π": "p",
                    "ρ": "r",
                    "σ": "s",
                    "ς": "s",
                    "τ": "t",
                    "υ": "y",
                    "φ": "f",
                    "χ": "ch",
                    "ψ": "ps",
                    "ω": "o",
                    "ει": "i",
                    "οι": "i",
                    "υι": "i",
                    "αι": "e",
                    "ου": "u",
                    "αυ": "av,af",
                    "ευ": "ev,ef",
                    "μπ": "b,mb",
                    "ντ": "d,nd",
                    "τζ": "dz",
                    "γγ": "ng",
                    "γκ": "gk,ng",
                    " ": " ",
                    "e": "e",
                    "i": "i",
                    "d": "d",
                    "z": "z",
                    "n": "n",
                    "g": "g",
                    "f": "f",
                    "b": "b",
                    "u": "u",
                },
                toIPA: {
                    "gk": "g",
                    "g": "ɣ",
                    "a": "ɑ",
                    "e": "ɛ",
                    "ch": "χ",
                    "ng": "ŋ",
                    "dh": "ð",
                    "th": "θ",
                    "y": "j",
                },
                transliteration_explanations: {
                    "γ": "'y' before e and i sounds, otherwise 'g'",
                    "αυ": "'av' before voiced consonants , 'af' before un-voiced",
                    "ευ": "'ev' before voiced consonants , 'ef' before un-voiced",
                    "μπ": "'b' word-initially, otherwise 'mb'",
                    "ντ": "'d' word-initially, otherwise 'nd'",
                    "γκ": "'g' word-initially, otherwise 'ng'"
                },
                specialLetters: [],
                levelList: [
                    {
                        letters: ["ν","β","ρ","α","ι"],
                        words: {
                            "Ιράν": "Iran",
                        },
                    },
                    {
                        letters: ["ς","λ","φ","κ","ε"],
                        words: {
                            "Σλοβενία": "Slovenia",
                            "Καλιφόρνια": "California",
                        },
                    },
                    {
                        letters: ["η","ο","ω","δ","π","τ"],
                        words: {
                            "Νεβάδα": "Nevada",
                            "Κόστα Ρίκα": "Costa Rica",
                            "Πακιστάν": "Pakistan",
                            "Περσεφόνη": "Persephone",
                        },
                    },
                    {
                        letters: ["μ","ξ","υ","γ"],
                        words: {
                            "ξενοφοβία": "xenophobia",
                            "Τελ Αβίβ": "Tel Aviv",
                        },
                    },
                    {
                        letters: ["γ","ζ","θ","χ"],
                        words: {
                            "καλλιγραφία": "calligraphy",
                            "Μεξικό": "Mexico",
                            "Θεσσαλονίκη": "Thessaloniki",
                        },
                    },
                    {
                        letters: ["αι", "ει", "οι", "υι", "ου"],
                        words: {
                            "Αλεξάνδρεια": "Alexandria",
                            "Παραγουάη": "Paraguay",
                            "Σωκράτης": "Socrates",
                        },
                    },
                    {
                        newletters: ["μπ", "ντ", "τζ", "γγ"],
                        words: {
                            "Τζόρτζια": "Georgia",
                            "Μπουτάν": "Bhutan",
                            "Τζαμάικα": "Jamaica",
                        },
                    },
                    {
                        tip: "This lesson will reference voiced versus unvoiced consonants. Voiced consonants involve vibration of the throat ('m', 'n', 'h' etc) while unvoiced don't ('t', 'k', 'p' etc).",
                        newletters: ["αυ", "ευ", "γκ"],
                        words: {
                            "αυτοκινητόδρομος": "highway",
                            "κοινοβουλευτικός": "parliamentary",
                            "Ανγκόλα": "Angola",
                        },
                    },
                ],
            },
        },
    },
    georgian: {
        bicameral: false,
        comingSoon: false,
        users: 4500000,
        location: ["Georgia"],
        languages: ["Georgian", "Mingrelian", "Laz", "Svan"],
        difficulty: 2,
        case: false,
        info: "Three Georgian scripts have existed since at least the 5th century. Today the Mkhedruli script is in use, which notably does not have capital letters.",
        langs: {
            georgian: {
                specialLetters: [],
                transliteration_explanations: {},
                alphabet: {
                    "ა": "a",
                    "ბ": "b",
                    "გ": "g",
                    "დ": "d",
                    "ე": "e",
                    "ვ": "v",
                    "ზ": "z",
                    "თ": "t",
                    "ი": "i",
                    "კ": "k'",
                    "ლ": "l",
                    "მ": "m",
                    "ნ": "n",
                    "ო": "o",
                    "პ": "p'",
                    "ჟ": "zh",
                    "რ": "r",
                    "ს": "s",
                    "ტ": "t'",
                    "უ": "u",
                    "ფ": "p",
                    "ქ": "k",
                    "ღ": "gh",
                    "ყ": "q'",
                    "შ": "sh",
                    "ჩ": "ch",
                    "ც": "ts",
                    "ძ": "dz",
                    "წ": "ts'",
                    "ჭ": "ch'",
                    "ხ": "kh",
                    "ჯ": "j",
                    "ჰ": "h",
                },
                toIPA: {
                    "zh": "ʒ",
                    "gh": "ʁ",
                    "sh": "ʃ",
                    "ch": "tʃ",
                    "ch'": "tʃ'",
                    "kh": "χ",
                    "j": "dʒ",
                    "a": "ɑ",
                    "e": "ɛ",
                    "o": "ɔ",
                },
                levelList: [
                    {
                        letters: ["ა","თ","ი"],
                        words: {"ათი": "ten"},
                    },
                    {
                        letters: ["ე","რ","მ"],
                        words: {"არა": "no","მერე": "later","მთა": "mountain"},
                    },
                    {
                        letters: ["ბ","გ","ო"],
                        words: {"ორი": "two","ერთი": "one"},
                    },
                    {
                        letters: ["დ","ჯ","ს"],
                        words: {"სად": "where?","გამარჯობა": "hello"},
                    },
                    {
                        letters: ["ლ","უ","ქ"],
                        words: {"ქართული": "georgian","გმადლობთ": "thanks (formal)","მადლობა": "thanks (informal)"},
                    },
                    {
                        letters: ["ხ","ფ","ნ"],
                        words: {"დამეხმარეთ": "help!","ფრთხილად": "look out!","ინგლისური": "english"},
                    },
                    {
                        letters: ["შ","ვ","ც"],
                        words: {"შორის": "between","მარცხნივ": "left","მარჯვნივ": "right"},
                    },
                    {
                        letters: ["ჰ","ძ","ჩ"],
                        words: {"ჰაეროვნება": "lightness","ბრძანდებით": "you are (formal)","ჩრდილოეთი": "north"},
                    },
                    {
                        letters: ["ღ","ჟ","ზ"],
                        words: {"აღმოსავლეთი": "east","ამჟამად": "currently","საზღვარი": "border"},
                    },
                    {
                        tip: "Non-aspirated consonants are consonants where no puff of air comes after pronouncing the letter, indicated with an apostrophe (')",
                        letters: ["პ","კ","ტ"],
                        words: {"პარასკევი": "friday","დეკემბერი": "december", "აეროპორტი": "airport"},
                    },
                    {
                        letters: ["ყ","წ","ჭ"],
                        words: {"ყურძენი": "grapes","წყალი": "water","ჭიანჭველასებრნი": "ants"},
                    },
                ],
            },
        },
    },
    tifinagh: {
        bicameral: false,
        comingSoon: false,
        users: 12000000,
        location: ["Morocco", "Algeria", "Tunisia", "Libya"],
        languages: ["Amazigh"],
        difficulty: 2,
        case: false,
        info: "The modern neo-Tifinagh alphabet is a relatively recent innovation of a precursor writing system called Tifinagh which is thousands of years old. The Amazigh languages of North Africa are often written in Latin or Arabic alphabets. However, the Tifinagh alphabet is official in Morocco and is becoming popular among young Amazigh speakers in other areas of North Africa. The examples words used here are from Central Atlas Tamazight.",
        langs: {
            atlas: {
                transliteration_explanations: {},
                specialLetters: ["ḍ", "ḥ", "ṛ", "ṣ", "ṭ", "ẓ", "ʷ"],
                alphabet: {
                    "ⴰ": "a",
                    "ⴱ": "b",
                    "ⴳ": "g",
                    "ⴷ": "d",
                    "ⴹ": "ḍ",
                    "ⴻ": "e",
                    "ⴼ": "f",
                    "ⴽ": "k",
                    "ⵀ": "h",
                    "ⵃ": "ḥ",
                    "ⵄ": "'",
                    "ⵅ": "kh",
                    "ⵇ": "q",
                    "ⵉ": "i",
                    "ⵊ": "j",
                    "ⵍ": "l",
                    "ⵎ": "m",
                    "ⵏ": "n",
                    "ⵓ": "u",
                    "ⵔ": "r",
                    "ⵕ": "ṛ",
                    "ⵖ": "gh",
                    "ⵙ": "s",
                    "ⵚ": "ṣ",
                    "ⵛ": "sh",
                    "ⵜ": "t",
                    "ⵟ": "ṭ",
                    "ⵡ": "w",
                    "ⵢ": "y",
                    "ⵣ": "z",
                    "ⵥ": "ẓ",
                    "ⵯ": "ʷ",
                },
                levelList: [
                    {
                        letters: ["ⴰ","ⵣ","ⵓ", "ⵍ"],
                        words: {"ⴰⵣⵓⵍ": "hello"},
                    },
                    {
                        letters: ["ⵔ","ⵎ","ⵜ"],
                        words: {"ⴰⵣⵣⴰⵔ": "hair","ⴰⵔⴰⵎ": "tuesday","ⵜⴰⵎⴰⵔⵜ": "a beard"},
                    },
                    {
                        letters: ["ⴱ","ⵙ","ⵉ"],
                        words: {"ⴱⴰⵍⵎⴰ": "swamp","ⵙⵎⵎⵓⵙ": "five", "ⵜⵓⵔⵜⵉⵜ": "garden"},
                    },
                    {
                        letters: ["ⵡ","ⵛ"],
                        words: {"ⵜⵉⵣⵉⵣⵡⵉⵜ": "bee","ⵜⴰⵛⵛⵍⵜ": "horned viper"},
                    },
                    {
                        letters: ["ⴳ","ⴷ","ⴹ"],
                        words: {"ⵉⴳⵔ": "a field","ⵜⵓⴳⴷⵓⵜ": "democracy","ⴰⴳⴹⵉⴹ": "bird"},
                    },
                    {
                        letters: ["ⴼ","ⴽ","ⵀ"],
                        words: {"ⴰⴼⴰⵍⴽⵓ": "falcon","ⵜⵉⴷⴷⵓⴽⴽⵍⴰ": "friendship","ⴰⵎⵀⴰⴷ": "thursday"},
                    },
                    {
                        letters: ["ⵃ","ⵄ","ⵅ"],
                        words: {"ⴰⵃⵉⴷⵓⵙ": "traditional amazigh performance","ⴰⵄⵔⴰⴱ": "arab","ⵉⵅⴼ": "head"},
                    },
                    {
                        letters: ["ⴻ","ⵇ","ⵊ"],
                        words: {"ⵜⴰⵎⴻⴷⴷⵉⵜ": "evening","ⴰⵇⵛⵎⵉⵔ": "rock","ⴰⵊⴷⴷⵉⴳ": "a flower"},
                    },
                    {
                        letters: ["ⵏ","ⵕ","ⵖ"],
                        words: {"ⵜⴰⴼⵓⵏⴰⵙⵜ": "cow","ⴽⵕⴰⴹ": "three","ⵜⴰⵎⴰⵣⵉⵖⵜ": "tamazight (the amazigh language)"},
                    },
                    {
                        letters: ["ⵚ","ⵟ","ⵢ"],
                        words: {"ⵙⴹⵉⵚ": "six","ⵜⵉⵟⵟⴰⵡⵉⵏ": "eyes","ⵜⴰⵢⵔⵉ": "love"},
                    },
                    {
                        tip: "The letter ⵯ represents a small 'w' sound after a consonant, which we will indicate with a ʷ",
                        letters: ["ⵥ","ⵯ"],
                        words: {"ⵉⵕⵥⵥⵉ": "wasp","ⴰⵎⴷⴷⴰⴽⴽⵯⵍ": "friend","ⵜⵉⵍⴳⴳⵯⵉⵜ": "a bridge"},
                    },
                ],
                toIPA: {
                    "a": "æ",
                    "e": "ə",
                    "u": "ʊ",
                    "ḍ": "dˤ",
                    "ḥ": "ħ",
                    "ṛ": "rˤ",
                    "ṣ": "sˤ",
                    "ṭ": "tˤ",
                    "ẓ": "zˤ",
                    "'": "ʕ",
                    "gh": "ɣ",
                    "j": "ʒ",
                    "kh": "χ",
                    "sh": "ʃ",
                    "ʷ": "w",
                    "y": "j",
                },
            },
        },
    },
    armenian: {
        bicameral: true,
        comingSoon: false,
        users:  6700000,
        location: ["Armenia", "Nagorno Karabakh", "Javakhk"],
        languages: ["Armenian"],
        difficulty: 2,
        case: true,
        info: "The Armenian alphabet was invented by Mesrop Mashtots in 405 CE. Presently it is only used for the Armenian language. This website will teach you the Eastern Armenian dialect.",
        langs: {
            armenian: {
                transliteration_explanations: {
                    "և": "'yev' word-initially, otherwise 'ev'",
                    "ո": "'vo' word-initially, otherwise 'o'",
                    "ե": "'ye' word-initially, otherwise 'e'",
                },
                levelList: [
                    {
                        letters: ["օ", "ր"],
                        words: {
                            "օր": "day",
                        },
                    },
                    {
                        tip: "Some letters have different pronunciations when they are at the beginning of a word.",
                        letters: ["պ", "ե", "կ"],
                        words: {
                            "րոպե": "minute",
                            "երեկ": "yesterday",
                        },
                    }, 
                    {
                        letters: ["և", "վ", "ա", "բ", "ի"],
                        words: {
                            "վերև": "uphill",
                            "բիբար": "pepper",
                            "բարև": "hello",
                        },
                    },
                    {
                        letters: ["ը", "ն", "զ"],
                        words: {
                            "ինը": "nine",
                            "զրո": "zero",
                        },
                    },
                    {
                        letters: ["ու", "թ", "ո", "յ"],
                        words: {
                            "երկու": "two",
                            "ութ": "eight",
                            "այո": "yes (polite)",
                        },
                    },
                    {
                        letters: ["տ", "ս", "շ"],
                        words: {
                            "տասներկու": "twelve",
                            "շատ": "a lot",
                            "տասնյոթ": "seventeen",
                        },
                    }, 
                    {
                        letters: ["է", "գ", "դ"],
                        words: {"դաշտէ": "field", "գիշեր": "night", "օդակայան": "airport"},
                    },
                    {
                        letters: ["ժ", "լ", "խ"],
                        words: {"տեսարժան": "attractions", "լոգարան": "a bathroom", "խոզանակ": "toothbrush"},
                    },
                    {
                        letters: ["ծ","հ","ձ"],
                        words: {"վիրավորված": "injured", "հանգիստ": "quiet", "ձուկ": "fish"},
                    },
                    {
                        letters: ["ղ", "ճ", "մ"],
                        words: {"մակարոնեղեն": "noodles", "նախաճաշ": "breakfast", "մրսածության": "cold (disease)"},
                    },
                    {
                        letters: ["չ", "ջ", "ռ", "ց"],
                        words: {"տասնչորս": "fourteen", "նարնջագույն": "orange", "ռեստորաններ": "restaurants", "հեռուստացույց": "television"},
                    },
                    {
                        letters: ["փ", "ք", "ֆ"],
                        words: {"փողոց": "street", "ընթրիք": "supper", "ֆունտեր": "pounds (currency)"},
                    },
                ],
                alphabet: {
                    "ա":"a",
                    "բ":"b",
                    "գ":"g",
                    "դ":"d",
                    "ե":"ye,e",
                    "զ":"z",
                    "է":"e",
                    "ը":"ə",
                    "թ":"t'",
                    "ժ":"ž",
                    "ի":"i",
                    "լ":"l",
                    "խ":"x",
                    "ծ":"c",
                    "կ":"k",
                    "հ":"h",
                    "ձ":"j",
                    "ղ":"ł",
                    "ճ":"č",
                    "մ":"m",
                    "յ":"j",
                    "ն":"n",
                    "շ":"š",
                    "ո":"vo,o",
                    "չ":"č'",
                    "պ":"p",
                    "ջ":"ǰ",
                    "ռ":"ṙ",
                    "ս":"s",
                    "վ":"v",
                    "տ":"t",
                    "ր":"r",
                    "ց":"c'",
                    "փ":"p",
                    "ք":"k",
                    "և":"yev,ev",
                    "օ":"ō",
                    "ֆ":"f",
                    "ու": "u",
                },
                specialLetters: ["č", "ə", "ǰ", "ł", "ō", "ṙ", "š", "ž"],
                toIPA: {
                    "a": "ɑ",
                    "e": "ɛ",
                    "o": "ɔ",
                    "ō": "o",
                    "ye": "je",
                    "yev":"jev",
                    "ev": "ev",
                    "ž": "ʒ",
                    "c": "ts",
                    "j": "dz",
                    "ł": "ʁ",
                    "č": "tʃ",
                    "t'": "tʰ",
                    "č'": "tʃʰ",
                    "c'": "tsʰ",
                    "p'": "pʰ",
                    "k'": "kʰ",
                    "ǰ": "dʒ",
                    "š": "ʃ",
                    "ṙ": "r",
                    "r": "ɾ",
                    "x": "χ",
                },
            },
        },
    },
    /*
    arabic: {
        bicameral: false,
        transliteration_explanations: {},
        comingSoon: true,
        alphabet: {},
        users:  660000000,
        specialLetters: [],
        location: ["North Africa", "Southwestern Asia"],
        languages: ["Arabic", "Persian", "Urdu", "Uyghur", "others"],
        difficulty: 3,
        case: true,
        info: "The Arabic alphabet is by over 300 million Arabs throughout North Africa and the Middle East. As Islam spread, the Arabic alphabet was adapted to all sorts of new languages, from Malay to Wolof to Kazakh. The Arabic alphabet is written from right to left.",
        levelList: [
            {},
            {},
        ],
    }, */
 /*
    coptic: {
        bicameral: false,
        transliteration_explanations: {},
        comingSoon: true,
        alphabet: {},
        users:  10000000,
        specialLetters: [],
        location: ["Egypt"],
        languages: ["Coptic"],
        difficulty: 1,
        case: true,
        info: "The Coptic language is the descendant of Ancient Egyptian, though in modern times it is only used by Egypt's Christian minority, the Copts, in religious contexts. While the Coptic alphabet looks like Greek, the language itself is more closely related to Arabic and Hebrew albeit distantly.",
        levelList: [
            {},
            {},
        ],
    }, */
    hebrew: {
        bicameral: false,
        comingSoon: false,
        users: 10000000,
        location: ["Israel"],
        languages: ["Hebrew", "Yiddish", "Ladino"],
        difficulty: 3,
        case: false,
        info: "The Hebrew alphabet has been used by the Jewish people for thousands of years, and it was the writing system used to transcribe the Torah (Old Testament), a holy text in Judaism, Christianity, and Islam. Today the alphabet is principally used for Hebrew, but also for over a dozen other Jewish languages around the world. It is written from right to left.",
        langs: {
            hebrew: {
                transliteration_explanations: {},
                specialLetters: [],
                alphabet: {
                    "א": "",
                    "בּ": "b",
                    "ב": "v",
                    "ג": "g",
                    "ד": "d",
                    "ה": "h",
                    "ז": "z",
                    "ח": "ch",
                    "ט": "t",
                    "י": "y",
                    "כּ": "k",
                    "כ": "ch",
                    "ך": "ch",
                    "ל": "l",
                    "מ": "m",
                    "ם": "m",
                    "נ": "n",
                    "ן": "n",
                    "ס": "s",
                    "ע": "",
                    "פּ": "p",
                    "פ": "f",
                    "ף": "f",
                    "צ": "tz",
                    "ץ": "tz",
                    "ק": "k",
                    "ר": "r",
                    "שׁ": "sh",
                    "שׂ": "s",
                    "ת": "t",
                    "וּ": "u",
                    "וֹ": "o",
                    "ו": "v",
                    "ְX": "",
                    "ֱX": "e",
                    "ֲX": "a",
                    "ֳX": "o",
                    "ִX": "i",
                    "ֵX": "e",
                    "ֶX": "e",
                    "ַX": "a",
                    "ָX": "a",
                    "ֻX": "u",
                    "ֹX": "o",
                    //
                    "b": "b",
                    "k": "k",
                    "p": "p",
                    "s": "s",
                    "h": "h",
                    "o": "o",
                    "u": "u",
                    "a": "a",
                    "e": "e",
                    "i": "i",
                },
                toIPA: {
                    "tz": "ts",
                    "ch": "χ",
                    "sh": "ʃ",
                    "a": "ɑ",
                    "e": "ɛ",
                    "y": "j",
                },
                levelList: [
                    {
                        tip: "Markings called 'niqqud' are put under letters to indicate vowels. These will be displayed under the letter 'X' in some examples. 'Niqqud' are optional in most Hebrew text (with the notable exception of Jewish prayers and the Torah) but they are important for learners.",
                        letters: ["ה", "ַX", "ר", "ְX"],
                        words: {"הַר": "mountain"},
                    },
                    {
                        letters: ["א", "ת", "ָX"],
                        words: {"אַתְ": "you (female)", "אַתָה": "you (male)"},
                    },
                    {
                        letters: ["ִX", "בּ", "י", "ד"],
                        words: {"בַּיִת": "house", "יָד": "hand"},
                    },
                    {
                        letters: ["ֵX", "ל", "ב"],
                        words: {"תֵל": "hill", "אָבִיב": "spring"},
                    },
                    {
                        letters: ["ס", "פ", "נ"],
                        words: {"סְפָרַד": "spain", "יַרְדֵן": "jordan", "יָוָן": "greece"},
                    },
                    {
                        letters: ["וּ", "מ", "צ"],
                        words: {"סוּרְיָה": "syria", "מִצְרַיִם": "egypt",},
                    },
                    {
                        letters: ["שׁ", "ט", "ג"],
                        words: {"יְרוּשָׁלַיִם": "jerusalem", "אַפְגָנִיסְטָן": "afghanistan"},
                    },
                    {
                        letters: ["וּ", "ז", "פּ"],
                        words: {"הוֹדוּ": "india", "בְּרָזִיל": "brazil", "פִילִיפִּינִים": "philippines"},
                    },
                    {
                        letters: ["ו", "ֶX", "ע", "ק"],
                        words: {"טַיְוָן": "taiwan", "סֶרְבְּיָה": "serbia", "עִירַאק": "iraq"},
                    },
                    {
                        letters: ["ח", "ֻX", "ֲX"],
                        words: {"שֻׁלְחַן": "table", "אֲסֵפָה": "assembly"},
                    },
                    {
                        letters: ["ֱX", "ֳX", "ֹX"],
                        words: {"אֱמֶת": "truth", "צִפֳּרִים‎": "birds", "יַהֲלוֹם‎": "diamond"},
                    },
                    {
                        letters: ["כ", "כּ", "שׂ"],
                        words: {"כָּחֹל": "blue", "הֲלָכָה": "jewish religious law", "יִשְׂרָאֵל": "israel"},
                    },
                ],
            },
        },
    },
}