ipa = {
    "": "silent",
    "ʔ": "[i] in uh[-]oh",
    "ɘ": "between [i] in b[i]t and [u] in [u]nder",
    "ɤ": "[oo] in f[oo]t",
    "ɨ": "[i] in [i]ll",
    "ju": "[u] in h[u]ge",
    "ja": "[ya] in [ya]rn",
    "jo": "[yo] in [yo]del",
    "je": "[ye] in [ye]s",
    "jev": "[yev] in wh[yev]er",
    "tʰ": "[t] in [t]all, with a small release of air",
    "tʃʰ": "[ch] in [ch]alk, with a small release of air",
    "tsʰ": "[ts] in le[ts], with a small release of air",
    "pʰ": "[p] in [p]lay, with a small release of air",
    "kʰ": "[k] in [k]id, with a small release of air",
    "dʒʰ": "[j] in [j]am, with a small release of air", //SOUND
    "ɒ": "[ough] in th[ough]", //SOUND
    "ɭ": "[l] with the tip of your tongue curling back", //SOUND
    "ʋ": "in between [v] and [w]", //SOUND
    "ʈ": "[t] but farther back in the mouth",
    "ʈʰ": "[t] but farther back in the mouth, and with a small release of air",
    "vo": "[vo] in [vo]te",
    "ʂ": "short [sh] in [sh]arp",
    "ɕ": "long [sh] in [sh]eer",
    "f": "[f] in [face]",
    "ɑ": "[a] in [a]lso",
    "aa": "lengthened [a] in [a]lso",
    "b": "[b] in [b]ean",
    "g": "[g] in [g]reat",
    "d": "[d] in [d]ark",
    "ɛ": "[e] in [e]very",
    "v": "[v] in [v]alue",
    "z": "[z] in [z]ipper",
    "t": "[t] in [t]all",
    "i": "[i] in sk[i]",
    "k": "[k] in [k]id",
    "l": "[l] in [l]emon",
    "m": "[m] in [m]elon",
    "n": "[n] in [n]obody",
    "ɔ": "[ough] in [ough]t",
    "o": "[ow] in l[ow]",
    "p": "[p] in [p]lay",
    "ʒ": "[z] in sei[z]ure",
    "r": "[r] in [r]un, but rolled",
    "s": "[s] in [s]alt",
    "u": "[u] in d[u]de",
    "ʁ": "like the French uvular [r]",
    "ʃ": "[sh] in [sh]ell",
    "ʃt": "[sht] in [sht]etl",
    "tʃ": "[ch] in [ch]alk",
    "ʃtʃ": "[shch] in pu[shch]air",
    "ɪ": "[i] in b[i]t",
    "ts": "[ts] in ne[ts]",
    "dz": "[ds] in li[ds]",
    "χ": "hard [ch] in Lo[ch]",
    "dʒ": "[j] in [j]am",
    "h": "[h] in [h]eart",
    "k'": "like [k] in [k]id but with the throat closed",
    "t'": "like [t] in [t]all with the throat closed",
    "p'": "like [p] in [p]lay with the throat closed",
    "q": "like [k] but farther back",
    "q'": "like [k] but farther back, with the throat closed",
    "ts'": "like [ts] in ne[ts] with the throat closed",
    "tʃ'": "like [ch] in [ch]ild with the throat closed",
    "w": "[w] in [w]ater",
    "æ": "[a] in h[a]t",
    "ə": "[a] in tun[a]",
    "ʊ": "[u] in p[u]t",
    "dˤ": "[d] in [d]ark, but more emphatic",
    "ħ": "whispered [h]",
    "rˤ": "rolled [r], but more emphatic",
    "sˤ": "[s] in [s]alt, but more emphatic",
    "tˤ": "[t] in [t]all, but more emphatic",
    "zˤ": "[z] in [z]ipper, but more emphatic",
    "ʕ": "uvular [r] as a vowel, no English equivalent",
    "ɣ": "uvular [g]",
    "j": "[y] in [y]arn",
    "ɾ": "[r] in [r]ed",
    "ev": "[ev] in [ev]ery",
    "av": "[av]ocado",
    "af": "[awf] in [awf]ul",
    "ef": "[eff] in [eff]ort",
    "ŋ": "[ng] in ri[ng]",
    "mb": "[mb] in la[mb]",
    "nd": "[nd] in e[nd]",
    "ks": "[x] in e[x]tra",
    "ð": "[th] in [th]is",
    "θ": "[th] in [th]ing",
    "ɟ": "[gy] in ma[gy]ar",
    "c": "[cky] in ba[cky]ard",
    "ʎ": "[lli] in mi[lli]on",
    "ɲ": "[ñ] in jalape[ñ]o",
    "ɖʐ": "like [j] in [j]am, but harder",
    "ʐ": "like [z] in a[z]ure, but harder",
    "tʂ": "soft [ch] sound",
    "tɕ": "hard [ch] sound",
    "ɓ": "in between [b] and [p]",
    "ɗ": "like [d] but farther back",
    "ƴ": "a shorter [y]",
    "ji": "[yee] as in [yee]t",
    "ɛj": "[a] in [a]te",
    "aj": "[i] in f[i]re",
    "oj": "[oy] in t[oy]",
    "ą": "nasal [an] like in fl[an]",
    "į": "nasal [in] like in d[in]e",
    "ǫ": "nasal [on] like in c[on]e",
    "aį": "nasal [ine] like in f[ine]",
    "oį": "nasal [oin] like in gr[oin]",
    "k~g": "between [k] and [g]",
    "p~b": "between [p] and [b]",
    "t~d": "between [t] and [d]",
    "br": "[br] as in [br]ain",
    "e": "[ay] in m[ay]",
    "y": "[u] in r[u]mor, but much briefer",
    "ø": "[i] in h[i]t but with the lips rounded",
    "la": "[la] in [la]va",
    "ɯ": "[oo] in g[oo]se",
    "ko": "[ko] in [ko]ala",
    "hi": "[hi] in a[hi] tuna",
    "tsu": "[tsu] in [tsu]nami",
    "te": "[te] in [te]ll",
    "so": "[so] in [so]da",
    "ɮ": "between [l] and [zh]",
    "ɵ": "[oo] in f[oo]t",
}
